/**
 * Logo 目录:simple-icons slug 精选(v1 ~200 常用品牌,按类别分组)。
 * id 即 simple-icons slug,经 /__market/proxy 取 https://cdn.jsdelivr.net/npm/simple-icons@13/icons/<slug>.svg。
 * slug 真实性:T6 冒烟对 pinned CDN 全量校验。
 */
export interface LogotypeEntry {
  /** simple-icons slug(如 react) */
  id: string;
  name: string;
  category: 'tech' | 'social' | 'dev' | 'cloud' | 'finance' | 'media' | 'gaming' | 'design' | 'shopping' | 'productivity' | 'ai';
}

export const LOGOTYPES: LogotypeEntry[] = [
  // ---- tech 消费与硬件(26) ----
  { id: 'apple', name: 'Apple', category: 'tech' },
  { id: 'google', name: 'Google', category: 'tech' },
  { id: 'samsung', name: 'Samsung', category: 'tech' },
  { id: 'huawei', name: 'Huawei', category: 'tech' },
  { id: 'xiaomi', name: 'Xiaomi', category: 'tech' },
  { id: 'sony', name: 'Sony', category: 'tech' },
  { id: 'panasonic', name: 'Panasonic', category: 'tech' },
  { id: 'lg', name: 'LG', category: 'tech' },
  { id: 'nvidia', name: 'NVIDIA', category: 'tech' },
  { id: 'amd', name: 'AMD', category: 'tech' },
  { id: 'intel', name: 'Intel', category: 'tech' },
  { id: 'oracle', name: 'Oracle', category: 'tech' },
  { id: 'dell', name: 'Dell', category: 'tech' },
  { id: 'asus', name: 'ASUS', category: 'tech' },
  { id: 'lenovo', name: 'Lenovo', category: 'tech' },
  { id: 'razer', name: 'Razer', category: 'tech' },
  { id: 'logitech', name: 'Logitech', category: 'tech' },
  { id: 'nikon', name: 'Nikon', category: 'tech' },
  { id: 'tesla', name: 'Tesla', category: 'tech' },
  { id: 'nokia', name: 'Nokia', category: 'tech' },
  { id: 'oneplus', name: 'OnePlus', category: 'tech' },
  { id: 'oppo', name: 'OPPO', category: 'tech' },

  // ---- social 社交内容(20) ----
  { id: 'facebook', name: 'Facebook', category: 'social' },
  { id: 'instagram', name: 'Instagram', category: 'social' },
  { id: 'whatsapp', name: 'WhatsApp', category: 'social' },
  { id: 'signal', name: 'Signal', category: 'social' },
  { id: 'telegram', name: 'Telegram', category: 'social' },
  { id: 'discord', name: 'Discord', category: 'social' },
  { id: 'slack', name: 'Slack', category: 'social' },
  { id: 'x', name: 'X', category: 'social' },
  { id: 'threads', name: 'Threads', category: 'social' },
  { id: 'bluesky', name: 'Bluesky', category: 'social' },
  { id: 'mastodon', name: 'Mastodon', category: 'social' },
  { id: 'reddit', name: 'Reddit', category: 'social' },
  { id: 'pinterest', name: 'Pinterest', category: 'social' },
  { id: 'tiktok', name: 'TikTok', category: 'social' },
  { id: 'youtube', name: 'YouTube', category: 'social' },
  { id: 'twitch', name: 'Twitch', category: 'social' },
  { id: 'wechat', name: 'WeChat', category: 'social' },
  { id: 'sinaweibo', name: 'Sina Weibo', category: 'social' },
  { id: 'bilibili', name: 'bilibili', category: 'social' },
  { id: 'tencentqq', name: 'Tencent QQ', category: 'social' },

  // ---- dev 开发(54) ----
  { id: 'github', name: 'GitHub', category: 'dev' },
  { id: 'gitlab', name: 'GitLab', category: 'dev' },
  { id: 'bitbucket', name: 'Bitbucket', category: 'dev' },
  { id: 'git', name: 'Git', category: 'dev' },
  { id: 'githubactions', name: 'GitHub Actions', category: 'dev' },
  { id: 'react', name: 'React', category: 'dev' },
  { id: 'vuedotjs', name: 'Vue.js', category: 'dev' },
  { id: 'angular', name: 'Angular', category: 'dev' },
  { id: 'svelte', name: 'Svelte', category: 'dev' },
  { id: 'nextdotjs', name: 'Next.js', category: 'dev' },
  { id: 'nuxtdotjs', name: 'Nuxt', category: 'dev' },
  { id: 'astro', name: 'Astro', category: 'dev' },
  { id: 'typescript', name: 'TypeScript', category: 'dev' },
  { id: 'javascript', name: 'JavaScript', category: 'dev' },
  { id: 'nodedotjs', name: 'Node.js', category: 'dev' },
  { id: 'python', name: 'Python', category: 'dev' },
  { id: 'rust', name: 'Rust', category: 'dev' },
  { id: 'go', name: 'Go', category: 'dev' },
  { id: 'swift', name: 'Swift', category: 'dev' },
  { id: 'kotlin', name: 'Kotlin', category: 'dev' },
  { id: 'php', name: 'PHP', category: 'dev' },
  { id: 'laravel', name: 'Laravel', category: 'dev' },
  { id: 'ruby', name: 'Ruby', category: 'dev' },
  { id: 'rubyonrails', name: 'Ruby on Rails', category: 'dev' },
  { id: 'cplusplus', name: 'C++', category: 'dev' },
  { id: 'sass', name: 'Sass', category: 'dev' },
  { id: 'tailwindcss', name: 'Tailwind CSS', category: 'dev' },
  { id: 'pnpm', name: 'pnpm', category: 'dev' },
  { id: 'npm', name: 'npm', category: 'dev' },
  { id: 'yarn', name: 'Yarn', category: 'dev' },
  { id: 'vite', name: 'Vite', category: 'dev' },
  { id: 'vitest', name: 'Vitest', category: 'dev' },
  { id: 'storybook', name: 'Storybook', category: 'dev' },
  { id: 'docker', name: 'Docker', category: 'dev' },
  { id: 'kubernetes', name: 'Kubernetes', category: 'dev' },
  { id: 'terraform', name: 'Terraform', category: 'dev' },
  { id: 'ansible', name: 'Ansible', category: 'dev' },
  { id: 'jenkins', name: 'Jenkins', category: 'dev' },
  { id: 'nginx', name: 'NGINX', category: 'dev' },
  { id: 'postgresql', name: 'PostgreSQL', category: 'dev' },
  { id: 'mysql', name: 'MySQL', category: 'dev' },
  { id: 'mongodb', name: 'MongoDB', category: 'dev' },
  { id: 'redis', name: 'Redis', category: 'dev' },
  { id: 'sqlite', name: 'SQLite', category: 'dev' },
  { id: 'elasticsearch', name: 'Elasticsearch', category: 'dev' },
  { id: 'graphql', name: 'GraphQL', category: 'dev' },
  { id: 'firebase', name: 'Firebase', category: 'dev' },
  { id: 'linux', name: 'Linux', category: 'dev' },
  { id: 'ubuntu', name: 'Ubuntu', category: 'dev' },
  { id: 'archlinux', name: 'Arch Linux', category: 'dev' },
  { id: 'vim', name: 'Vim', category: 'dev' },
  { id: 'xcode', name: 'Xcode', category: 'dev' },

  { id: 'dotnet', name: '.NET', category: 'dev' },
  { id: 'sublimetext', name: 'Sublime Text', category: 'dev' },
  // ---- cloud 云服务(14) ----
  { id: 'googlecloud', name: 'Google Cloud', category: 'cloud' },
  { id: 'cloudflare', name: 'Cloudflare', category: 'cloud' },
  { id: 'vercel', name: 'Vercel', category: 'cloud' },
  { id: 'netlify', name: 'Netlify', category: 'cloud' },
  { id: 'heroku', name: 'Heroku', category: 'cloud' },
  { id: 'digitalocean', name: 'DigitalOcean', category: 'cloud' },
  { id: 'hetzner', name: 'Hetzner', category: 'cloud' },
  { id: 'fastly', name: 'Fastly', category: 'cloud' },
  { id: 'flydotio', name: 'Fly.io', category: 'cloud' },
  { id: 'render', name: 'Render', category: 'cloud' },
  { id: 'supabase', name: 'Supabase', category: 'cloud' },
  { id: 'alibabacloud', name: 'Alibaba Cloud', category: 'cloud' },
  { id: 'scaleway', name: 'Scaleway', category: 'cloud' },

  // ---- finance 金融支付(15) ----
  { id: 'visa', name: 'Visa', category: 'finance' },
  { id: 'mastercard', name: 'Mastercard', category: 'finance' },
  { id: 'paypal', name: 'PayPal', category: 'finance' },
  { id: 'stripe', name: 'Stripe', category: 'finance' },
  { id: 'wise', name: 'Wise', category: 'finance' },
  { id: 'square', name: 'Square', category: 'finance' },
  { id: 'applepay', name: 'Apple Pay', category: 'finance' },
  { id: 'googlepay', name: 'Google Pay', category: 'finance' },
  { id: 'alipay', name: 'Alipay', category: 'finance' },
  { id: 'bitcoin', name: 'Bitcoin', category: 'finance' },
  { id: 'ethereum', name: 'Ethereum', category: 'finance' },
  { id: 'binance', name: 'Binance', category: 'finance' },
  { id: 'coinbase', name: 'Coinbase', category: 'finance' },
  { id: 'americanexpress', name: 'American Express', category: 'finance' },

  // ---- media 媒体娱乐(14) ----
  { id: 'netflix', name: 'Netflix', category: 'media' },
  { id: 'spotify', name: 'Spotify', category: 'media' },
  { id: 'applemusic', name: 'Apple Music', category: 'media' },
  { id: 'soundcloud', name: 'SoundCloud', category: 'media' },
  { id: 'youtubemusic', name: 'YouTube Music', category: 'media' },
  { id: 'lastdotfm', name: 'Last.fm', category: 'media' },
  { id: 'primevideo', name: 'Prime Video', category: 'media' },
  { id: 'crunchyroll', name: 'Crunchyroll', category: 'media' },
  { id: 'vlcmediaplayer', name: 'VLC Media Player', category: 'media' },
  { id: 'unsplash', name: 'Unsplash', category: 'media' },
  { id: 'behance', name: 'Behance', category: 'media' },
  { id: 'dribbble', name: 'Dribbble', category: 'media' },
  { id: 'substack', name: 'Substack', category: 'media' },
  { id: 'pixiv', name: 'pixiv', category: 'media' },

  // ---- gaming 游戏(14) ----
  { id: 'steam', name: 'Steam', category: 'gaming' },
  { id: 'epicgames', name: 'Epic Games', category: 'gaming' },
  { id: 'playstation', name: 'PlayStation', category: 'gaming' },
  { id: 'nintendo', name: 'Nintendo', category: 'gaming' },
  { id: 'nintendoswitch', name: 'Nintendo Switch', category: 'gaming' },
  { id: 'roblox', name: 'Roblox', category: 'gaming' },
  { id: 'unity', name: 'Unity', category: 'gaming' },
  { id: 'unrealengine', name: 'Unreal Engine', category: 'gaming' },
  { id: 'godotengine', name: 'Godot Engine', category: 'gaming' },
  { id: 'itchdotio', name: 'itch.io', category: 'gaming' },
  { id: 'riotgames', name: 'Riot Games', category: 'gaming' },
  { id: 'dota2', name: 'Dota 2', category: 'gaming' },
  { id: 'ea', name: 'EA', category: 'gaming' },

  // ---- design 设计创作(16) ----
  { id: 'figma', name: 'Figma', category: 'design' },
  { id: 'sketch', name: 'Sketch', category: 'design' },
  { id: 'canva', name: 'Canva', category: 'design' },
  { id: 'adobe', name: 'Adobe', category: 'design' },
  { id: 'adobephotoshop', name: 'Adobe Photoshop', category: 'design' },
  { id: 'adobeillustrator', name: 'Adobe Illustrator', category: 'design' },
  { id: 'adobeaftereffects', name: 'Adobe After Effects', category: 'design' },
  { id: 'adobepremierepro', name: 'Adobe Premiere Pro', category: 'design' },
  { id: 'blender', name: 'Blender', category: 'design' },
  { id: 'affinitydesigner', name: 'Affinity Designer', category: 'design' },
  { id: 'framer', name: 'Framer', category: 'design' },
  { id: 'webflow', name: 'Webflow', category: 'design' },
  { id: 'wordpress', name: 'WordPress', category: 'design' },
  { id: 'penpot', name: 'Penpot', category: 'design' },
  { id: 'excalidraw', name: 'Excalidraw', category: 'design' },
  { id: 'miro', name: 'Miro', category: 'design' },

  // ---- shopping 电商零售(10) ----
  { id: 'shopify', name: 'Shopify', category: 'shopping' },
  { id: 'woocommerce', name: 'WooCommerce', category: 'shopping' },
  { id: 'magento', name: 'Magento', category: 'shopping' },
  { id: 'amazon', name: 'Amazon', category: 'shopping' },
  { id: 'ebay', name: 'eBay', category: 'shopping' },
  { id: 'etsy', name: 'Etsy', category: 'shopping' },
  { id: 'ikea', name: 'IKEA', category: 'shopping' },
  { id: 'target', name: 'Target', category: 'shopping' },
  { id: 'walmart', name: 'Walmart', category: 'shopping' },
  { id: 'zalando', name: 'Zalando', category: 'shopping' },

  // ---- productivity 效率办公(16) ----
  { id: 'notion', name: 'Notion', category: 'productivity' },
  { id: 'todoist', name: 'Todoist', category: 'productivity' },
  { id: 'asana', name: 'Asana', category: 'productivity' },
  { id: 'clickup', name: 'ClickUp', category: 'productivity' },
  { id: 'jira', name: 'Jira', category: 'productivity' },
  { id: 'confluence', name: 'Confluence', category: 'productivity' },
  { id: 'linear', name: 'Linear', category: 'productivity' },
  { id: 'zapier', name: 'Zapier', category: 'productivity' },
  { id: 'n8n', name: 'n8n', category: 'productivity' },
  { id: 'googledrive', name: 'Google Drive', category: 'productivity' },
  { id: 'googledocs', name: 'Google Docs', category: 'productivity' },
  { id: 'gmail', name: 'Gmail', category: 'productivity' },
  { id: 'dropbox', name: 'Dropbox', category: 'productivity' },
  { id: 'zoom', name: 'Zoom', category: 'productivity' },
  { id: 'googlemeet', name: 'Google Meet', category: 'productivity' },

  // ---- ai 人工智能(12) ----
  { id: 'openai', name: 'OpenAI', category: 'ai' },
  { id: 'anthropic', name: 'Anthropic', category: 'ai' },
  { id: 'huggingface', name: 'Hugging Face', category: 'ai' },
  { id: 'tensorflow', name: 'TensorFlow', category: 'ai' },
  { id: 'pytorch', name: 'PyTorch', category: 'ai' },
  { id: 'opencv', name: 'OpenCV', category: 'ai' },
  { id: 'scikitlearn', name: 'scikit-learn', category: 'ai' },
  { id: 'jupyter', name: 'Jupyter', category: 'ai' },
  { id: 'ollama', name: 'Ollama', category: 'ai' },
  { id: 'langchain', name: 'LangChain', category: 'ai' },  { id: 'googlegemini', name: 'Google Gemini', category: 'ai' },

];
